export const constants = {
	DEV_CRI_BAV_API_URL: process.env.DEV_CRI_BAV_API_URL,
	DEV_IPV_BAV_STUB_URL: process.env.DEV_IPV_BAV_STUB_URL,
	DEV_BAV_EXPIRED_ACCESS_TOKEN: process.env.DEV_BAV_EXPIRED_ACCESS_TOKEN,
	DEV_BAV_MISSING_SUB_ACCESS_TOKEN: process.env.DEV_BAV_MISSING_SUB_ACCESS_TOKEN,
	DEV_BAV_TEST_HARNESS_URL: process.env.DEV_BAV_TEST_HARNESS_URL,
	DEV_BAV_SESSION_TABLE_NAME: process.env.DEV_BAV_SESSION_TABLE_NAME,
	DEV_BAV_PERSONAL_IDENTITY_TABLE_NAME: process.env.DEV_BAV_PERSONAL_IDENTITY_TABLE_NAME,
	VC_SIGNING_KEY_ID: process.env.VC_SIGNING_KEY_ID,
	DNS_SUFFIX: process.env.DNS_SUFFIX,
};
