version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "bav-test-harness-regression-sk"
s3_prefix = "bav-test-harness"
region = "eu-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
parameter_overrides = "CodeSigningConfigArn=\"none\" Environment=\"dev\" PermissionsBoundary=\"none\" SecretPrefix=\"none\" VpcStackName=\"vpc-cri\" BackendStack=\"bav-cri-api-regression-sk\""
image_repositories = []
