export enum AuthSessionState {
	BAV_SESSION_CREATED = "BAV_SESSION_CREATED",
	BAV_DATA_RECEIVED = "BAV_DATA_RECEIVED",
	BAV_AUTH_CODE_ISSUED = "BAV_AUTH_CODE_ISSUED",
	BAV_ACCESS_TOKEN_ISSUED = "BAV_ACCESS_TOKEN_ISSUED",
	BAV_CRI_VC_ISSUED = "BAV_CRI_VC_ISSUED"
}
