export enum MessageCodes {
	SERVER_ERROR = "SERVER_ERROR",
	MISSING_CONFIGURATION = "MISSING_CONFIGURATION",
	INVALID_AUTH_CODE = "INVALID_AUTH_CODE",
	SESSION_NOT_FOUND = "SESSION_NOT_FOUND",
	SESSION_EXPIRED = "SESSION_EXPIRED",
	SESSION_ALREADY_EXISTS = "SESSION_ALREADY_EXISTS",
}
