export enum TxmaEventNames {
	BAV_CRI_START = "BAV_CRI_START",
	BAV_COP_REQUEST_SENT = "BAV_COP_REQUEST_SENT",
	BAV_COP_RESPONSE_RECEIVED = "BAV_COP_RESPONSE_RECEIVED",
	BAV_EXPERIAN_REQUEST_SENT = "BAV_EXPERIAN_REQUEST_SENT",
	BAV_EXPERIAN_RESPONSE_RECEIVED = "BAV_EXPERIAN_RESPONSE_RECEIVED",
	BAV_CRI_VC_ISSUED = "BAV_CRI_VC_ISSUED",
	BAV_CRI_END = "BAV_CRI_END",
	BAV_CRI_SESSION_ABORTED = "BAV_CRI_SESSION_ABORTED",
}
